# Exported from Render on 2026-07-27T16:24:28Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: Cyptopulse
      runtime: docker
      
